### ISSUE TITLE
floor(x, y) can produce a result greater than x when y is negative

### ISSUE THREAD

**Issue by theastrallyforged** [m-ender/alice#3]
Reproduction:

```
9 7R m / @
        O 
```

This `floor(9, -7)` pushes `14`, even though `14 > 9`.

> Cardinal `m`: **Floor.** Pop `y`. Pop `x`. Push the greatest multiple of `y` which is not greater than `x`.

**Comment by m-ender** [comment]
Sorry that this took me forever to get around to, but it's finally fixed! In hindsight I feel like this behaviour might actually have been more useful (so you can use it as a ceiling command with negative divisors), but that functionality can still be recovered by flipping the sign of the other operand and the result.
